#! /bin/bash

while getopts s:t:d: opt ; do
    case "$opt" in
        s)
            script="$OPTARG"
            ;;
        t|d)
            delay="$OPTARG"
            ;;
        *)
            exit 1
            ;;
    esac
done
shift $((OPTIND-1))

if [[ $# -lt 1 ]]; then
    echo "SUBID must be specified"
    exit 1
fi

if [[ -n $delay ]]; then
    sleep $((delay*3600-300))
fi

if [[ -n "$script" ]]; then
    bin/vultr startupscript.destroy SCRIPTID="$script"
fi
bin/vultr server.destroy SUBID="$1"
